###################################################################

# Created by write_sdc on Tue Nov  8 22:47:34 2016

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
set_driving_cell -lib_cell INVX1 [get_ports start_transmit]
set_driving_cell -lib_cell INVX1 [get_ports lpi]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[63]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[62]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[61]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[60]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[59]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[58]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[57]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[56]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[55]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[54]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[53]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[52]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[51]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[50]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[49]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[48]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[47]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[46]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[45]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[44]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[43]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[42]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[41]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[40]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[39]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[38]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[37]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[36]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[35]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[34]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[33]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[32]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[31]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[30]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[29]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[28]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[27]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[26]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[25]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[24]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[23]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[22]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[21]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[20]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[19]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[18]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[17]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[16]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[15]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[14]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[13]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[12]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[11]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[10]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[9]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[8]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[7]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[6]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[5]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[4]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_data[0]}]
set_driving_cell -lib_cell INVX1 [get_ports pkt_empty]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_ctrl[7]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_ctrl[6]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_ctrl[5]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_ctrl[4]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_ctrl[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_ctrl[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_ctrl[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_ctrl[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[31]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[30]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[29]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[28]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[27]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[26]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[25]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[24]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[23]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[22]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[21]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[20]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[19]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[18]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[17]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[16]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[15]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[14]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[13]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[12]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[11]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[10]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[9]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[8]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[7]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[6]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[5]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[4]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {pkt_crc[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {bvalidin[7]}]
set_driving_cell -lib_cell INVX1 [get_ports {bvalidin[6]}]
set_driving_cell -lib_cell INVX1 [get_ports {bvalidin[5]}]
set_driving_cell -lib_cell INVX1 [get_ports {bvalidin[4]}]
set_driving_cell -lib_cell INVX1 [get_ports {bvalidin[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {bvalidin[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {bvalidin[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {bvalidin[0]}]
create_clock [get_ports clks.clk]  -name clk  -period 2.7  -waveform {0 1.35}
set_clock_uncertainty 0.25  [get_clocks clk]
set_input_delay -clock clk  0.6  [get_ports start_transmit]
set_input_delay -clock clk  0.6  [get_ports lpi]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[63]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[62]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[61]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[60]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[59]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[58]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[57]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[56]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[55]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[54]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[53]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[52]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[51]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[50]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[49]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[48]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[47]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[46]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[45]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[44]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[43]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[42]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[41]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[40]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[39]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[38]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[37]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[36]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[35]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[34]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[33]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[32]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[31]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[30]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[29]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[28]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[27]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[26]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[25]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[24]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[23]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[22]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[21]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[20]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[19]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[18]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[17]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[16]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[15]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[14]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[13]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[12]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[11]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[10]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[9]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[8]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[7]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[6]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[5]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[4]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[3]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[2]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[1]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_data[0]}]
set_input_delay -clock clk  0.6  [get_ports pkt_empty]
set_input_delay -clock clk  0.6  [get_ports {pkt_ctrl[7]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_ctrl[6]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_ctrl[5]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_ctrl[4]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_ctrl[3]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_ctrl[2]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_ctrl[1]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_ctrl[0]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[31]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[30]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[29]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[28]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[27]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[26]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[25]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[24]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[23]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[22]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[21]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[20]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[19]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[18]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[17]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[16]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[15]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[14]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[13]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[12]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[11]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[10]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[9]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[8]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[7]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[6]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[5]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[4]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[3]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[2]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[1]}]
set_input_delay -clock clk  0.6  [get_ports {pkt_crc[0]}]
set_input_delay -clock clk  0.6  [get_ports {bvalidin[7]}]
set_input_delay -clock clk  0.6  [get_ports {bvalidin[6]}]
set_input_delay -clock clk  0.6  [get_ports {bvalidin[5]}]
set_input_delay -clock clk  0.6  [get_ports {bvalidin[4]}]
set_input_delay -clock clk  0.6  [get_ports {bvalidin[3]}]
set_input_delay -clock clk  0.6  [get_ports {bvalidin[2]}]
set_input_delay -clock clk  0.6  [get_ports {bvalidin[1]}]
set_input_delay -clock clk  0.6  [get_ports {bvalidin[0]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXC[3]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXC[2]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXC[1]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXC[0]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[31]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[30]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[29]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[28]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[27]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[26]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[25]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[24]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[23]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[22]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[21]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[20]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[19]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[18]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[17]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[16]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[15]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[14]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[13]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[12]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[11]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[10]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[9]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[8]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[7]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[6]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[5]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[4]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[3]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[2]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[1]}]
set_output_delay -clock clk  0.3  [get_ports {xgmii_tx.TXD[0]}]
set_output_delay -clock clk  0.3  [get_ports xgmii_tx.TXCLK]
set_output_delay -clock clk  0.3  [get_ports pop_pkt]
set_output_delay -clock clk  0.3  [get_ports pop_crc]
set_output_delay -clock clk  0.3  [get_ports nxt_buf]
