#!/bin/sh -h 
PYTHONHOME=/apps/synopsys/VCSMX_NEW/etc/search/pyh
export PYTHONHOME
PYTHONPATH=/apps/synopsys/VCSMX_NEW/linux/lib/pylib27
export PYTHONPATH
LD_LIBRARY_PATH=/apps/synopsys/VCSMX_NEW/linux/lib:/apps/synopsys/VCSMX_NEW/linux/lib/pylib27
export LD_LIBRARY_PATH
/apps/synopsys/VCSMX_NEW/linux/bin/vcsfind_create_index.exe  -z  simv.daidir/debug_dump/fsearch/idents_98U75W.xml.gz  -o simv.daidir/debug_dump/fsearch/fsearch.db_tmp
\mv simv.daidir/debug_dump/fsearch/fsearch.db_tmp simv.daidir/debug_dump/fsearch/fsearch.db
